### PR TITLE
Added changes to allow for cross platform.

### PR DESCRIPTION
**Pull request by alaurie**
Changed $TempPath parameter to use [System.IO.Path]::GetTempPath() for cross platform temp management.

Changed creation of temp file to use New-TemporaryFile for cross platform temp file management.
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-temporaryfile?view=powershell-5.1

General formatting.

Tested on Debian 12 and now works with these changes.

### CODE REVIEW

**Comment by alaurie** [comment]
You could probably remove the Parameter of $TempPath entirely and just use New-TemporaryFile

**Comment by DanGough** [comment]
Thanks, I'll review this shortly!

I didn't use New-TemporaryFile as it doesn't give any control over the location or name format. I did have the temp path default to the output location at first, as most browsers do. However terminating the script with CTRL+C ends up leaving those temp files locked until the objects are released or process closed... so for now I'm hiding those under temp! 😬

**Comment by DanGough** [comment]
I will partially merge this:

- [System.IO.Path]::GetTempPath() - Great
- Check for Windows when doing file blocking/unblocking - Great
- Replacing " with ' where appropriate - Yes, I normally do this too and not sure why I didn't here!
- New-TemporaryFile - I will leave this out as it then doesn't even make use of the temp path that was just fixed.
- Formatting changes - My style doesn't match all the changes and I rely on VSCode's Alt+Shift+F auto formatting, so I will create formatting rules and include with the project instead.

**Review by DanGough — APPROVED** [review]

**Comment by alaurie** [comment]
> I will partially merge this:
> 
> * [System.IO.Path]::GetTempPath() - Great
> * Check for Windows when doing file blocking/unblocking - Great
> * Replacing " with ' where appropriate - Yes, I normally do this too and not sure why I didn't here!
> * New-TemporaryFile - I will leave this out as it then doesn't even make use of the temp path that was just fixed.
> * Formatting changes - My style doesn't match all the changes and I rely on VSCode's Alt+Shift+F auto formatting, so I will create formatting rules and include with the project instead.

Thanks, yeah the formatting changes were more of a mistake on my part. On my setup I format on save and use OBS style brackets and some other stuff, so they got brought in with my commit.

**Pull request merged**
